from fpdf import FPDF
import streamlit as st

class PDF(FPDF):
    def header(self):
        # We can add custom headers here if needed, but for resumes, clean is better.
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by AI Resume Builder', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 6, title, 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        self.set_font('Arial', '', 10)
        self.multi_cell(0, 5, body)
        self.ln()

class ResumeGenerator:
    def __init__(self, data):
        self.data = data
        self.pdf = PDF()
        self.pdf.add_page()
        self.pdf.set_auto_page_break(auto=True, margin=15)

    def generate(self, filename="resume.pdf"):
        # --- HEADER (Contact Info) ---
        contact = self.data.get('contact_info', {})
        name = f"{contact.get('first_name', '')} {contact.get('last_name', '')}".upper()
        details = f"{contact.get('email', '')} | {contact.get('phone', '')}"
        if contact.get('linkedin'):
            details += f" | {contact.get('linkedin', '')}"
        if contact.get('location'):
            details += f" | {contact.get('location', '')}"

        self.pdf.set_font('Arial', 'B', 16)
        self.pdf.cell(0, 10, name, 0, 1, 'C')
        
        self.pdf.set_font('Arial', '', 10)
        self.pdf.cell(0, 5, details, 0, 1, 'C')
        self.pdf.ln(5)
        
        self.pdf.line(10, self.pdf.get_y(), 200, self.pdf.get_y())
        self.pdf.ln(5)

        # --- SUMMARY ---
        summary = self.data.get('summary', '')
        if summary:
            self.pdf.chapter_title("PROFESSIONAL SUMMARY")
            self.pdf.chapter_body(summary)

        # --- SKILLS ---
        skills = self.data.get('skills', [])
        if skills:
            self.pdf.chapter_title("TECHNICAL SKILLS")
            skills_str = ", ".join(skills)
            self.pdf.chapter_body(skills_str)

        # --- EXPERIENCE ---
        experience = self.data.get('experience', [])
        if experience:
            self.pdf.chapter_title("PROFESSIONAL EXPERIENCE")
            for exp in experience:
                # Title & Company
                self.pdf.set_font('Arial', 'B', 10)
                title_line = f"{exp.get('role', '')} | {exp.get('company', '')}"
                self.pdf.cell(0, 5, title_line, 0, 1)
                
                # Duration
                self.pdf.set_font('Arial', 'I', 9)
                self.pdf.cell(0, 5, exp.get('duration', ''), 0, 1)
                
                # Description
                self.pdf.set_font('Arial', '', 10)
                self.pdf.multi_cell(0, 5, exp.get('description', ''))
                self.pdf.ln(3)

        # --- PROJECTS ---
        projects = self.data.get('projects', [])
        if projects:
            self.pdf.chapter_title("KEY PROJECTS")
            for proj in projects:
                self.pdf.set_font('Arial', 'B', 10)
                title = f"{proj.get('title', '')}"
                if proj.get('tech'):
                    title += f" ({proj.get('tech', '')})"
                self.pdf.cell(0, 5, title, 0, 1)
                
                self.pdf.set_font('Arial', '', 10)
                self.pdf.multi_cell(0, 5, proj.get('description', ''))
                self.pdf.ln(3)

        # --- EDUCATION ---
        education = self.data.get('education', [])
        if education:
            self.pdf.chapter_title("EDUCATION")
            for edu in education:
                self.pdf.set_font('Arial', 'B', 10)
                self.pdf.cell(0, 5, f"{edu.get('degree', '')}", 0, 1)
                
                self.pdf.set_font('Arial', '', 10)
                school_line = f"{edu.get('school', '')} | {edu.get('year', '')}"
                if edu.get('grade'):
                    school_line += f" | {edu.get('grade', '')}"
                self.pdf.cell(0, 5, school_line, 0, 1)
                self.pdf.ln(3)
        
        # --- CERTIFICATIONS ---
        certs = self.data.get('certifications', [])
        if certs:
            self.pdf.chapter_title("CERTIFICATIONS")
            for cert in certs:
                self.pdf.cell(0, 5, f"- {cert}", 0, 1)

        return self.pdf.output(dest='S').encode('latin-1')
